"""Inicial

Revision ID: 917bd151c8a3
Revises: 
Create Date: 2025-05-05 17:52:14.544809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917bd151c8a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('raza', sa.String(length=100), nullable=False),
    sa.Column('proposito', sa.String(length=100), nullable=False),
    sa.Column('ganaderia', sa.String(length=100), nullable=False),
    sa.Column('corral', sa.String(length=100), nullable=False),
    sa.Column('num_animal', sa.String(length=50), nullable=False),
    sa.Column('codigo_referencia', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.DateTime(), nullable=False),
    sa.Column('peso_nacimiento', sa.Float(), nullable=False),
    sa.Column('padre_id', sa.String(length=36), nullable=True),
    sa.Column('madre_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chequeos_salud',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('animal_id', sa.String(length=36), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('diagnostico', sa.Text(), nullable=False),
    sa.Column('tratamiento', sa.Text(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=False),
    sa.Column('realizado_por', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos_reproductivos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('animal_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('resultado', sa.Text(), nullable=False),
    sa.Column('realizado_por', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('propietario_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pesos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('animal_id', sa.String(length=36), nullable=False),
    sa.Column('peso_kg', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('registrado_por', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produccion_leche',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('animal_id', sa.String(length=36), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('cantidad_litros', sa.Float(), nullable=False),
    sa.Column('registrado_por', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tratamientos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('animal_id', sa.String(length=36), nullable=False),
    sa.Column('medicamento', sa.String(length=255), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('registrado_por', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_finca',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vacunas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('animal_id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('registrado_por', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacunas')
    op.drop_table('usuarios')
    op.drop_table('usuario_finca')
    op.drop_table('tratamientos')
    op.drop_table('produccion_leche')
    op.drop_table('pesos')
    op.drop_table('farms')
    op.drop_table('eventos_reproductivos')
    op.drop_table('chequeos_salud')
    op.drop_table('animals')
    # ### end Alembic commands ###
