app = 'vacas-196gmw'
primary_region = 'bog'

[build]

[http_service]
  internal_port = 5050
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  DATABASE_URL = "mysql://root:OxarsznSbmtNaOBPqAgAixiCKQzjiIEw@turntable.proxy.rlwy.net:40215/railway"
  SECRET_KEY = "dabisin04."
